package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestGenerateWritesBothLocalesWithoutDates(t *testing.T) {
	root := &cobra.Command{Use: "leo", Short: "test root"}
	root.AddCommand(&cobra.Command{Use: "child", Short: "test child", Run: func(*cobra.Command, []string) {}})
	docsRoot := t.TempDir()

	if err := generate(root, docsRoot); err != nil {
		t.Fatal(err)
	}

	for _, path := range []string{
		filepath.Join(docsRoot, "reference", "commands", "leo.md"),
		filepath.Join(docsRoot, "reference", "commands", "leo_child.md"),
		filepath.Join(docsRoot, "en", "reference", "commands", "leo.md"),
		filepath.Join(docsRoot, "en", "reference", "commands", "leo_child.md"),
	} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		text := string(data)
		if !strings.HasPrefix(text, "---\ntitle:") {
			t.Fatalf("%s has no frontmatter", path)
		}
		if strings.Contains(text, "Auto generated by") {
			t.Fatalf("%s contains a generated date", path)
		}
	}
}
